turtlecoin/turtle-explorer-js

pages/blockchain_transaction.html

```diff
+ Payment ID decoding
- Patment ID decoding
```

Fixed typo

---

config.js
index.html
pages/home.html

Daemon changes added application/json content-type flag into the getinfo response which caused the block explorer to throw an error b/c it was trying to parse an object that was already parsed. Added in a catch so it works for people using either version of the daemon.

add donation address to footer and fix issue w/ trying to re-parse json due to content-type change

---

js/pools.js
pages/pools.html

plus about 1,000 code cleanup operations in the pools.js file. 
lots of dedup/kiss/abstraction, indentation confusion.
fixes issue #11

enable proper pool sorting

---

js/pools.js

sorry for the bad implementation because I didn't have test data. thanks to `http://turtle.link/config.js` for the extra test data!

fix sorting when network2 values are loading via API.

---

css/themes/turtle/bootstrap.css
css/themes/turtle/style.css
index.html

start new turtlecoin theme based on the `slate` bootswatch.
I used the same format of pulling in a bootswatch theme and modifying values / editing style.css to override. Not sure if there's interest to be adding build tools for scss/less so we can actually just edit a bootstrap `variables.scss` file.
Closes #14

WIP: improve styling to be more turtley 

---

index.html
js/check_txn.js
js/crypto_utils.js
pages/check_txn.html

Modeled after the Monero code at https://github.com/luigi1111/xmr.llcoins.net so there may be some license adjustments we need to do here. 
Currently deployed at http://trtl.world/temp/#check_txn for testing. I'll work on getting a PR into the Turtlecoin repo so that people can get their Txn private keys to test with, for now view secret is needed.

added transaction check using priv txn or view keys

---

index.html

Make the menu drop down collapse after an item is selected on mobile.

Close menu after click/touch on mobile

---

js/pools.js
pages/pools.html

deployed live at: https://explorer.trtlpwr.cc/#pools
closes #21

fix pools table sorting again

---

pages/pools.html

this alignment has always driven me nuts :100: 
new look:

center pools pie chart

---

pages/pools.html

Fixing this: https://i.imgur.com/WD7v8FT.png

Incorrect display of Network Hashrate and Pools hashrate

---

js/pools.js

YIKERS: https://i.imgur.com/VTjABq9.png

Fix for disappearing H/s on update

---

js/color-hash.js
js/pools.js
pages/pools.html

add persistent colors for pool names (hashed color codes based on name)
add "unknown" hash rate to put chart into perspective
sort pools by hashrate so it looks fine fine fine

enhance pools pie chart!

---

js/pools.js

Standardize on spaces, as they're used elsewhere in the project over nbsps.
Closes #30

Cleanup unused / dead code on pools page

---

js/color-hash.js
js/pools.js

Implement pie/doughnut chart redesign for pools page.

---

js/main.js

change date format from DD-MM-YYYY to YYYY-MM-DD

---

pages/home.html

Fixed indentation and transactions plot on graph on home page

Fixed indentation and transactions plot on graph

---

config.php
q/hashrate/index.php
q/height/index.php
q/reward/index.php
q/supply/index.php
q/util.php

all the /q/ API stuff didn't work on my deployment because of hard coded URLs for localhost daemon.
someone came into Discord complaining about it and I thought i'd fix it, and clean it up a bit while I was in there.

make PHP API great again!

---

js/pools.js

Fixes final pool fee down to 0.001%
Test before merging.

Fix for floating point rounding error

---

config.js

Add pool http://turtleminers.club to the list

Add new pool - turtleminers.club

---

config.js

Reverts turtlecoin/block-explorer#59

Revert "Add new pool - turtleminers.club"

---

config.js
pages/home.html

This makes it easier to fork for other currencies

put total supply in variable for easier forking

---

js/pools.js

Fixing rounding

---

config.js

Added trtl.hackerknowledge.de PPS Pool

add trtl.hackerknowledge.de PPS Pool
